# artifactory-cleanup.yaml
artifactory-cleanup:
  server: https://prashanttest.jfrog.io/artifactory
  user: pqrs16374@gmail.com
  password: cmVmdGtuOjAxOjAwMDAwMDAwMDA6SVVqN2NkS3JqdjBIdkJEb3NjOGQxNEJoSk5w
  policies:
    - name: Conan - delete files older than 60 days
      rules:
        - rule: RepoByMask
          mask: "*generic*"
       # - rule: PropertyNeq
       #   property_key: key-name
        #  property_value: 1
        #- rule: DeleteOlderThan
         # days: 7
