# .github/workflows/reusable-semantic-release.yml
name: Reusable Semantic Release Workflow

on:
  workflow_call:
    outputs:
      previous_tag:
        description: "Previous version tag"
        value: ${{ jobs.release.outputs.previous_tag }}
      next_tag:
        description: "Next version tag"
        value: ${{ jobs.release.outputs.next_tag }}
      release_type:
        description: "Type of release"
        value: ${{ jobs.release.outputs.release_type }}
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      previous_tag: ${{ steps.set-output.outputs.PREV_TAG }}
      next_tag: ${{ steps.set-output.outputs.NEXT_TAG }}
      release_type: ${{ steps.set-output.outputs.RELEASE_TYPE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install --no-save \
            semantic-release@22.0.12 \
            @semantic-release/commit-analyzer@11.1.0 \
            conventional-changelog-conventionalcommits@7.0.2 \
            @semantic-release/exec@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/release-notes-generator@12.1.0 \
            @semantic-release/changelog@6.0.3

      - name: Semantic Release
        id: semantic
        run: |
          node .releaserc.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Output Variables
        id: set-output
        run: |
          # Fallback logic inside the script
          PREV_TAG=${{ steps.semantic.outputs.lastRelease.version || '0.0.0' }}
          NEXT_TAG=${{ steps.semantic.outputs.nextRelease.version }}
          
          if [ -z "$NEXT_TAG" ]; then
            NEXT_TAG=$PREV_TAG
          fi
          
          RELEASE_TYPE=${{ steps.semantic.outputs.nextRelease.type || 'patch' }}

          echo "DEBUG: PREV_TAG=v$PREV_TAG"
          echo "DEBUG: NEXT_TAG=v$NEXT_TAG"
          echo "DEBUG: RELEASE_TYPE=$RELEASE_TYPE"




          
          
          # Write to environment files for the rest of the workflow
          echo "PREV_TAG=v$PREV_TAG" >> $GITHUB_ENV
          echo "NEXT_TAG=v$NEXT_TAG" >> $GITHUB_ENV
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
          
          # Use the new environment files method for outputs
          echo "PREV_TAG=v$PREV_TAG" >> $GITHUB_OUTPUT
          echo "NEXT_TAG=v$NEXT_TAG" >> $GITHUB_OUTPUT
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_OUTPUT
