name: Semantic Release Workflow

on:
  workflow_call:
    outputs:
      previous_tag:
        description: "Previous version tag"
        value: ${{ jobs.release.outputs.previous_tag }}
      next_tag:
        description: "Next version tag"
        value: ${{ jobs.release.outputs.next_tag }}
      release_type:
        description: "Type of release"
        value: ${{ jobs.release.outputs.release_type }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      previous_tag: ${{ steps.semantic.outputs.PREV_TAG }}
      next_tag: ${{ steps.semantic.outputs.NEXT_TAG }}
      release_type: ${{ steps.semantic.outputs.RELEASE_TYPE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branches }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Semantic Release
        id: semantic
        run: |
          npm install --no-save \
            semantic-release@22.0.12 \
            @semantic-release/commit-analyzer@11.1.0 \
            conventional-changelog-conventionalcommits@7.0.2 \
            @semantic-release/exec@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@9.2.6 \
            @semantic-release/release-notes-generator@12.1.0 \
            @semantic-release/changelog@6.0.3
          
          node .releaserc.mjs 

          echo "PREV_TAG=v${{ steps.semantic.outputs.lastRelease.version }}" >> $GITHUB_ENV
          echo "NEXT_TAG=v${{ steps.semantic.outputs.nextRelease.version }}" >> $GITHUB_ENV
          echo "RELEASE_TYPE=${{ steps.semantic.outputs.nextRelease.type }}" >> $GITHUB_ENV
