name: Reusable Semantic Release Workflow

on:
  workflow_call:
    outputs:
      next_tag:
        description: "Next version tag"
        value: ${{ jobs.release.outputs.next_tag }}
permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.semantic_release.outputs.NEXT_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --no-save \
            semantic-release@22.0.12 \
            @semantic-release/commit-analyzer@11.1.0 \
            conventional-changelog-conventionalcommits@7.0.2 \
            @semantic-release/exec@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/release-notes-generator@12.1.0 \
            @semantic-release/changelog@6.0.3
            npx semantic-release  || true

      - name: Run Semantic Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run semantic release and capture the output
          # Capture the last release tag and next release tag using git
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "LAST_TAG=$LAST_TAG"

          # If semantic-release generates a new tag, capture it
          if [ -f ".nextRelease" ]; then
            NEXT_TAG=$(cat .nextRelease)
            echo "New release tag: $NEXT_TAG"
            echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          else
            # If no new release is generated, fallback to the last tag
            echo "No new release, using last tag: $LAST_TAG"
            echo "NEXT_TAG=$LAST_TAG" >> $GITHUB_ENV
          fi

      - name: Use Version
        run: echo "Version to use:${{ env.NEXT_TAG }}"

      - name: Save Tag to Environment
        run: |
          echo "VERSION=${{ env.NEXT_TAG }}" >> $GITHUB_ENV
