name: "Semantic Release"

on:
  workflow_call:
    outputs:
      new_version:
        description: "The newly generated semantic version"
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Essential for semantic-release to access all commits

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release @semantic-release/changelog @semantic-release/git

      - name: Run semantic-release
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set the new version number
        id: get_version
        run: echo "version=${{ steps.semantic.outputs.nextRelease.version }}" >> $GITHUB_OUTPUT
