name: "Semantic Versioning"

on:
  workflow_call:
    outputs:
      new_version:
        description: "The newly generated semantic version"
        value: ${{ jobs.release.outputs.version }}
    secrets:
      custom_token:
        required: true  # Rename 'github_token' to 'custom_token' or similar
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.nextRelease.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Pacificdubey/resuable-workflow
          fetch-depth: 0
      #- name: Checkout code
       # uses: actions/checkout@v2
        #with:
         # fetch-depth: 0
          
      - run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '16'  # Make sure this is 16 or higher

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        id: semantic
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.custom_token }} 
