name: "Generate Semantic Version"

on:
  workflow_call:
    outputs:
      new_version:
        description: "The newly generated semantic version"
        value: ${{ steps.semantic.outputs.next_version }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Run semantic-release
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output next version
        if: steps.semantic.outputs.next_version
        run: echo "new_version=${{ steps.semantic.outputs.next_version }}" >> $GITHUB_ENV
