name: Repository Creation Task

on: [push]
  #workflow_call:

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud

    - name: Extract Branch Name
      id: extract_branch
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        # Set the environment variable with sanitized branch name
        echo "repository=$(echo $BRANCH_NAME | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Debug Information
      run: |
        echo "Branch Name: ${{ env.BRANCH_NAME }}"
        echo "Sanitized Repository Name: ${{ env.repository }}"

    - name: Create Repository
      run: |
        REPO_NAME="${{ env.repository }}-repo"
        echo "Creating repository: $REPO_NAME"
        # Debug: Check if the repository exists
        RESPONSE=$(jfrog rt curl -X GET /api/repositories/$REPO_NAME || true)
        echo "Response: $RESPONSE"
        if echo "$RESPONSE" | grep -q "404"; then
          # Create the repository if it does not exist
          jfrog rt rc --json='{"rclass": "local", "packageType": "maven", "repoLayoutRef": "maven-2-default"}' $REPO_NAME
        else
          echo "Repository $REPO_NAME already exists or an error occurred"
        fi
