name: Repository Creation Task

on: [push]
  #workflow_call:

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud

    - name: Extract Branch Name
      id: extract_branch
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Debug Information
      run: |
        echo "Branch Name: ${{ env.BRANCH_NAME }}"

    - name: Create Repository
      run: |
        REPO_NAME="${{ env.BRANCH_NAME }}-repo"
        echo "Creating repository: $REPO_NAME"
        # Check if the repository already exists
        RESPONSE=$(jfrog rt curl -X GET /api/repositories/$REPO_NAME || true)
        if [ -z "$RESPONSE" ]; then
          # Create the repository if it does not exist
          jfrog  repo-create --json='{"rclass": "local", "packageType": "maven", "repoLayoutRef": "maven-2-default"}' $REPO_NAME
        else
          echo "Repository $REPO_NAME already exists"
        fi
