name: Repository Creation Task

on: [push]
  #workflow_call:

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud

    - name: Extract Branch Name
      id: extract_branch
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        # Set the environment variable with sanitized branch name
        echo "repository=$(echo $BRANCH_NAME | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Debug Information
      run: |
        echo "Branch Name: ${{ env.BRANCH_NAME }}"
        echo "Sanitized Repository Name: ${{ env.repository }}"

    - name: Check Repository Existence
      id: check_repo
      run: |
        REPO_NAME="${{ env.repository }}-repo"
        echo "Checking if repository exists: $REPO_NAME"
        RESPONSE=$(jfrog rt curl -X GET "/api/repositories/$REPO_NAME" || true)
        echo "Response: $RESPONSE"
        if echo "$RESPONSE" | grep -q "404"; then
          echo "Repository does not exist"
          echo "CREATE_REPO=true" >> $GITHUB_ENV
        else
          echo "Repository exists"
          echo "CREATE_REPO=false" >> $GITHUB_ENV
        fi

    - name: Create Repository
      if: env.CREATE_REPO == 'true'
      run: |
        REPO_NAME="${{ env.repository }}-repo"
        echo "Creating repository: $REPO_NAME"
        # Define the repository configuration JSON
        REPO_CONFIG=$(cat <<EOF
           {
             "rclass": "local",
             "packageType": "maven",
             "repoLayoutRef": "maven-2-default"
           }
          EOF
          )
        # Create the repository
        RESPONSE=$(jfrog rt rc --json="$REPO_CONFIG" "$REPO_NAME" 2>&1)
        echo "Response: $RESPONSE"
        if echo "$RESPONSE" | grep -q "400"; then
          echo "Failed to create repository: $REPO_NAME"
          exit 1
        fi
