name: Repository Creation Task

on: [push]
  #workflow_call:

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud
    - name: Extract Branch Name
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        echo "repository=$(echo $BRANCH_NAME | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Check and Create Repository
      run: |
        REPO_NAME=${{ env.repository }}-repo
        STATUS_CODE=$(jfrog rt curl -X GET "/api/repositories/$REPO_NAME" -I --silent | head -n 1 | awk '{print $2}')
        echo $STATUS_CODE
        # jfrog rt rc template/local-repo-template.json --vars repo=$REPO_NAME
        
