name: Repository Creation

on: [ push ]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      with:
        jfrog-version: 'latest'

    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: githubtest
        oidc-audience: aud

    - name: Extract Branch Name
      id: extract_branch
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Repository
      run: |
        REPO_NAME="${{ env.BRANCH_NAME }}-repo"
        # Check if the repository already exists
          jf rt rc templates/local-repo-template.json --vars key1=$REPO_NAME
